#!/usr/bin/env bash

[ "$1" = "-h" ] && usage && exit 0

# Prints usage help
function usage {
cat << _EOF_
Usage: delta-run-channel <agent-manager-ip-address> <agent-manager-port>
_EOF_
}

ssh $DELTA_CH "sudo java -jar delta-agent-channel-1.0-SNAPSHOT-jar-with-dependencies.jar $1 $2"