#!/bin/sh

# Run Agent Manager
java -Xdebug -Xrunjdwp:transport=dt_socket,server=y,suspend=y,address=5005 -jar ~/DELTA/manager/target/delta-manager-1.0-SNAPSHOT-jar-with-dependencies.jar ~/DELTA/config/manager_default.cfg
