#!/bin/bash
version=${1}

# Prints usage help
function usage {
    echo "Usage: setup-onos-delta <onos-version>" >&2
    echo "* supported ONOS version: 1.1, 1.6, 1.9" >&2
    exit 1
}

# Configure environment variables
export JAVA_HOME=/usr/lib/jvm/java-8-oracle
export ONOS_APPS=drivers,openflow,proxyarp,mobility,fwd

[ $# -lt 1 ] && usage
if [ -z $DELTA_ROOT ]; then
    echo "* Please setup DELTA bash_profile in your .bashrc"
    exit 1
fi

case $version in
    1.1|1.1.0)
        echo "Setting up ONOS 1.1.0 to AppAgent..."
        version=1.1.0
        ;;
    1.6|1.6.0)
        echo "Setting up ONOS 1.6.0 to AppAgent..."
        version=1.6.0
        ;;
    1.9|1.9.0)
        echo "Setting up ONOS 1.9.0 to AppAgent..."
        version=1.9.0
        ;;
    *) usage;;
esac

# get ONOS
ssh $DELTA_APP "
    sudo apt-get install unzip -y
    cd /tmp
    wget http://downloads.onosproject.org/release/onos-$version.zip
    unzip onos-$version.zip
    rm onos-$version.zip
"
scp $DELTA_ROOT/agents/apps/onos/onos-1.9/target/delta-agent-app-onos-$version-1.0-SNAPSHOT.jar $DELTA_APP:/tmp/
scp $DELTA_ROOT/tools/dev/app-agent-setup/onos/onos-$version-setup $DELTA_APP:/tmp/
scp $DELTA_ROOT/tools/dev/app-agent-setup/onos/run-onos-delta $DELTA_APP:/tmp/

# copy delta app agent
ssh $DELTA_APP cp /tmp/delta-agent-app-onos-$version-1.0-SNAPSHOT.jar /tmp/onos-$version/apache-karaf-3.0.8/deploy/

status=$?
echo # new line for prompt
exit $status