#!/bin/bash
onos_version=${1}


# Prints usage help
function usage {
    echo "Usage: delta-setup-onos <onos-version>" >&2
    echo "* supported ONOS version: 1.6, 1.9" >&2
    exit 1
}

# Configure environment variables
export JAVA_HOME=/usr/lib/jvm/java-8-oracle
export ONOS_APPS=drivers,openflow,proxyarp,mobility,fwd

[ $# -lt 1 ] && usage
if [ -z $DELTA_ROOT ]; then
    echo "* Please setup DELTA bash_profile in your .bashrc"
    exit 1
fi

case $onos_version in
    1.6|1.6.0)
        echo "Setting up ONOS 1.6.0 to AppAgent..."
        onos_version=1.6.0
        karaf_version=3.0.5
        ;;
    1.9|1.9.0)
        echo "Setting up ONOS 1.9.0 to AppAgent..."
        onos_version=1.9.0
        karaf_version=3.0.8
        ;;
    *) usage;;
esac

# get ONOS
ssh $DELTA_APP "
    sudo apt-get install unzip -y
    cd /tmp
    wget http://downloads.onosproject.org/release/onos-$onos_version.zip
    unzip onos-$onos_version.zip
    rm onos-$onos_version.zip
"
scp $DELTA_ROOT/agents/apps/onos/onos-$onos_version/target/delta-agent-app-onos-$onos_version-1.0-SNAPSHOT.jar $DELTA_APP:/tmp/
scp $DELTA_ROOT/tools/dev/app-agent-setup/onos/onos-$onos_version-setup $DELTA_APP:/tmp/
scp $DELTA_ROOT/tools/dev/app-agent-setup/onos/run-onos-delta $DELTA_APP:/tmp/

# copy delta app agent
ssh $DELTA_APP cp /tmp/delta-agent-app-onos-$onos_version-1.0-SNAPSHOT.jar /tmp/onos-$onos_version/apache-karaf-$karaf_version/deploy/

status=$?
echo # new line for prompt
exit $status