#!/usr/bin/env bash

onos_version=${1}

function usage {
    echo "Usage: delta-scp-onos <onos-version>" >&2
    echo "* supported ONOS version: 1.6, 1.9, 1.13.1" >&2
    exit 1
}

[ $# -lt 1 ] && usage
if [ -z $DELTA_ROOT ]; then
    echo "* Please setup DELTA bash_profile in your .bashrc"
    exit 1
fi

case $onos_version in
    1.6|1.6.0)
        echo "Setting up ONOS 1.6.0 to AppAgent..."
        onos_version=1.6.0
        karaf_version=3.0.5
        ;;
    1.9|1.9.0)
        echo "Setting up ONOS 1.9.0 to AppAgent..."
        onos_version=1.9.0
        karaf_version=3.0.8
        ;;
    1.13|1.13.1)
        echo "Starting ONOS 1.13.1 on AppAgent..."
        onos_version=1.13.1
        karaf_version=3.0.8
        ;;
    *) usage;;
esac

# copy delta app agent
scp $DELTA_ROOT/agents/apps/onos/onos-$onos_version/target/delta-agent-app-onos-$onos_version-1.0-SNAPSHOT.jar $DELTA_CP:~
ssh $DELTA_CP cp delta-agent-app-onos-$onos_version-1.0-SNAPSHOT.jar onos-$onos_version/apache-karaf-$karaf_version/deploy/
