#!/bin/bash -x
CR="\e[92m[DELTA] "
NOCR="\e[0m"

echo -e $CR"Install dependencies"$NOCR

scp install-ovs $DELTA_CP:~

ssh $DELTA_CP "
    sudo apt-get update
    sudo apt-get upgrade -y
    sudo apt-get install -y python-dev python-pip wget unzip git

    echo debconf shared/accepted-oracle-license-v1-1 select true | sudo debconf-set-selections
    echo debconf shared/accepted-oracle-license-v1-1 seen true | sudo debconf-set-selections

    sudo apt-get install software-properties-common -y
    sudo add-apt-repository ppa:webupd8team/java -y
    sudo apt-get update
    sudo apt-get install oracle-java8-installer oracle-java8-set-default -y
    sudo apt-get install -y libpcap-dev

    git clone https://github.com/mininet/mininet
    mininet/util/install.sh -nf

    ./install-ovs 2.5.4
"

echo -e $CR"Stop control plane container"$NOCR
sudo lxc-stop -n container-cp

echo -e $CR"Copy control plane container to channel container"$NOCR
sudo lxc-copy -n container-cp -N container-ch

echo -e $CR"Copy control plane container to data plane container"$NOCR
sudo lxc-copy -n container-cp -N container-dp

echo -e $CR"Start control plane container"$NOCR
sudo lxc-start -n container-cp -d

echo -e $CR"Start channel container"$NOCR
sudo lxc-start -n container-ch -d

echo -e $CR"Start data plane container"$NOCR
sudo lxc-start -n container-dp -d

echo -e $CR"Install mininet in container-dp"$NOCR
ssh $DELTA_DP "
    git clone https://github.com/mininet/mininet
    cd mininet
    mininet/util/install.sh -knfv
"
sudo route add -net 10.0.1.0/24 gw 10.0.3.13 dev lxcbr0
