#!/bin/sh

#Run virtual machines

str=$(vboxmanage list vms)
vm1=`echo $str | cut -d' ' -f1`
vm1=`echo $vm1 | tr -d '\"'`
vm2=`echo $str | cut -d' ' -f3`
vm2=`echo $vm2 | tr -d '\"'`
vm3=`echo $str | cut -d' ' -f5`
vm3=`echo $vm3 | tr -d '\"'`

vboxmanage startvm $vm1 --type headless
vboxmanage startvm $vm2 --type headless
vboxmanage startvm $vm3 --type headless
