#!/bin/bash
#
# Script to install static flow rules on OVS
#

sudo ovs-ofctl add-flow s3 in_port=1,actions=output:2
sudo ovs-ofctl add-flow s3 in_port=2,actions=output:1
sudo ovs-ofctl dump-flows s3

