#!/bin/bash

ssh $DELTA_CP '
    sudo apt-get update
    sudo apt-get install -y python-pip python-dev

    export LC_ALL="en_US.UTF-8"
    export LC_CTYPE="en_US.UTF-8"
    sudo dpkg-reconfigure locales

    sudo pip install ryu
    sudo pip install -U setuptools msgpack-python netaddr oslo.config ovs routes six tinyrpc webob
    sudo pip install eventlet==0.18.2
'
