#!/bin/bash

scp -r $DELTA_ROOT/agents/apps/ryu $DELTA_APP:~/
ssh $DELTA_APP "ryu-manager --verbose --observe-links ryu.app.simple_switch_13 ryu.topology ryu.app.gui_topology.gui_topology ryu/AppAgent.py"
