#!/bin/bash

AppName="ryu.app.simple_switch_13"
if [ "$1" = "1.0" ]; then
 AppName="ryu.app.simple_switch"
fi

scp -r $DELTA_ROOT/agents/apps/ryu $DELTA_APP:~/
ssh $DELTA_APP "ryu-manager --verbose --observe-links $AppName ryu.topology ryu.app.gui_topology.gui_topology ryu/AppAgent.py"
