#!/bin/bash
#
# Script to odl-helium dependencies on Ubuntu 14.04
#

export MAVEN=${MAVEN:-~/Applications/apache-maven-3.3.9}

export PATH="$PATH:$DELTA_ROOT/tools/bin"
export PATH="$PATH:$MAVEN/bin"

export MAVEN_OPTS='-Xmx2048m -XX:MaxPermSize=1024m'
export JAVA_HOME=/usr/lib/jvm/java-7-oracle/
