#!/bin/bash
#
# Script to distribute the compiled files to VMs
#

scp $DELTA_ROOT/agents/apps/opendaylight/opendaylight-oxygen/target/delta-agent-app-odl-oxygen-sr2-1.0-SNAPSHOT.jar $DELTA_CP:~/
ssh $DELTA_CP "cp ~/delta-agent-app-odl-oxygen-sr2-1.0-SNAPSHOT.jar ~/karaf-0.8.2/deploy"
