#!/bin/bash
#
# Script to install ODL dependencies on Ubuntu 14.04
#

# install jdk-1.7
echo debconf shared/accepted-oracle-license-v1-1 select true | sudo debconf-set-selections
echo debconf shared/accepted-oracle-license-v1-1 seen true | sudo debconf-set-selections

sudo apt-get install software-properties-common -y
sudo add-apt-repository ppa:webupd8team/java -y
sudo apt-get update
wget http://ftp.osuosl.org/pub/funtoo/distfiles/oracle-java/jdk-7u80-linux-x64.tar.gz
sudo mv jdk-7u80-linux-x64.tar.gz /var/cache/oracle-jdk7-installer/
sudo apt-get install oracle-java7-set-default git wget -y
sudo apt-get install ant unzip git -y

# install maven, karaf
cd; mkdir Downloads Applications
cd Downloads
wget http://archive.apache.org/dist/maven/maven-3/3.3.9/binaries/apache-maven-3.3.9-bin.tar.gz
tar -zxvf apache-maven-3.3.9-bin.tar.gz -C ../Applications/

cd ;
git clone https://github.com/opendaylight/controller.git odl-helium-sr3
cd odl-helium-sr3
git checkout release/helium-sr3

source ~/odl-helium-sr3-bash-profile

mvn clean install -Dcheckstyle.skip=True -DskipTests
