#!/bin/bash
ovs_version=${1}

if [ $# -ne 1 ]
then
    echo "Usage: ./install-ovs <ovs-version>"
    exit 0
fi

sudo apt-get install -y wget build-essential fakeroot debhelper autoconf automake libssl-dev pkg-config bzip2 openssl python-all procps python-qt4 python-zopeinterface python-twisted-conch dkms dh-python dh-autoreconf uuid-runtime

mkdir openvswitch
cd openvswitch

wget http://openvswitch.org/releases/openvswitch-$ovs_version.tar.gz
tar -zxvf openvswitch-$ovs_version.tar.gz
cd openvswitch-$ovs_version
DEB_BUILD_OPTIONS='parallel=8 nocheck' fakeroot debian/rules binary
cd ..

sudo dpkg -i libopenvswitch*.deb openvswitch-common*.deb openvswitch-datapath-dkms*.deb python-openvswitch*.deb openvswitch-pki*.deb openvswitch-switch*.deb
cd ..
rm -r openvswitch
