#!/bin/bash

echo "Start lxc-setup"
ssh $DELTA_APP "
    sudo apt-get update
    sudo apt-get upgrade -y
    sudo apt-get install -y python-dev python-pip
    sudo apt-get install -y git
    sudo apt-get install -y wget
    sudo apt-get install unzip

    echo debconf shared/accepted-oracle-license-v1-1 select true | sudo debconf-set-selections
    echo debconf shared/accepted-oracle-license-v1-1 seen true | sudo debconf-set-selections

    sudo apt-get install software-properties-common -y
    sudo add-apt-repository ppa:webupd8team/java -y
    sudo apt-get update
    sudo apt-get install oracle-java8-installer oracle-java8-set-default -y

    sudo apt-get install -y openvswitch-common openvswitch-switch
    git clone https://github.com/mininet/mininet
    cd mininet
    git checkout -b 2.2.1 2.2.1
"

scp $HOME/DELTA/tools/dev/lxc-setup/install.sh $DELTA_APP:/home/ubuntu/mininet/util/install.sh
ssh $DELTA_APP "
    mininet/util/install.sh -a
"

echo "Copy agent-controller"
sudo lxc-stop -n agent-controller
sudo lxc-copy -n agent-controller -N agent-channel
sudo lxc-copy -n agent-controller -N agent-host

echo "Create agent-channel and agent-host"
sudo lxc-start -n agent-controller -d
sudo lxc-start -n agent-channel -d
sudo lxc-start -n agent-host -d
