#!/bin/bash
CR="\e[92m[DELTA] "
NOCR="\e[0m"

echo -e $CR"Install lxc"$NOCR
sudo apt-get install -y lxc

echo -e $CR"Set default IP address"$NOCR
sudo cp dnsmasq.conf /etc/lxc/dnsmasq.conf

echo -e $CR"Create a container for control plane (container-cp)"$NOCR
sudo lxc-create -n container-cp -t ubuntu
