#!/bin/bash

if lsovs=`ls /etc/init.d/*openvswitch* 2>/dev/null`; then
    for s in $lsovs; do
        s=$(basename $s)
        sudo service $s stop
        sudo rm -f /etc/init.d/$s
        sudo update-rc.d -f $s remove
    done
fi

pkgs=`sudo dpkg --get-selections | grep openvswitch | awk '{ print $1; }'`
sudo dpkg -r $pkgs

