#!/bin/bash

#
# Script to install DELTA dependencies on Ubuntu 16.04
#

# install oracle-jdk 1.8
echo debconf shared/accepted-oracle-license-v1-1 select true | sudo debconf-set-selections
echo debconf shared/accepted-oracle-license-v1-1 seen true | sudo debconf-set-selections

sudo apt-get install software-properties-common -y
sudo add-apt-repository ppa:webupd8team/java -y
sudo apt-get update && sudo apt-get install oracle-java8-installer -y
sudo apt-get install oracle-java8-set-default -y
sudo apt-get install openjdk-8-jdk

# install unzip ant wget
sudo apt-get install unzip ant wget -y

# install maven
cd; mkdir Downloads Applications
cd Downloads
wget https://repo.maven.apache.org/maven2/org/apache/maven/apache-maven/3.3.9/apache-maven-3.3.9-bin.tar.gz
tar -zxvf apache-maven-3.3.9-bin.tar.gz -C ../Applications/
