# -*- mode: ruby -*-
# vi: set ft=ruby :
#
# Copyright 2016-present Open Networking Laboratory
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#      http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#

Vagrant.configure(2) do |config|

  if (/cygwin|mswin|mingw|bccwin|wince|emx/ =~ RUBY_PLATFORM) != nil
    config.vm.synced_folder ".", "/vagrant", mount_options: ["dmode=700,fmode=600"]
  else
    config.vm.synced_folder ".", "/vagrant"
  end

  config.vm.define "controller" do |d|
    d.vm.box = "ubuntu/trusty64"
    d.vm.hostname = "controller-vm"
    d.vm.network "private_network", ip: "10.100.100.11"
    d.vm.network "private_network", ip: "10.100.200.11"
    d.vm.provision :shell, path: "scripts/java8-oracle.sh"
    d.vm.provider "virtualbox" do |v|
      v.customize ["modifyvm", :id, "--nicpromisc2", "allow-all"]
      v.memory = 8192
      v.cpus = 2
    end
  end

  config.vm.define "channel" do |d|
    d.vm.box = "ubuntu/trusty64"
    d.vm.hostname = "channel-vm"
    d.vm.network "private_network", ip: "10.100.100.12"
    d.vm.network "private_network", ip: "10.100.200.12"
    d.vm.provision :shell, path: "scripts/java8-oracle.sh"
    d.vm.provision :shell, path: "scripts/mininet.sh"
    d.vm.provider "virtualbox" do |v|
      v.customize ["modifyvm", :id, "--nicpromisc2", "allow-all"]
      v.memory = 2048
    end
  end

  config.vm.define "mininet" do |d|
    d.vm.box = "ubuntu/trusty64"
    d.vm.hostname = "mininet-vm"
    d.vm.network "private_network", ip: "10.100.100.13"
    d.vm.network "private_network", ip: "10.100.200.13"
    d.vm.provision :shell, path: "scripts/java8-oracle.sh"
    d.vm.provision :shell, path: "scripts/mininet.sh"
    d.vm.provider "virtualbox" do |v|
      v.customize ["modifyvm", :id, "--nicpromisc2", "allow-all"]
      v.memory = 2048
    end
  end

end
