#!/bin/bash
# DELTA developer bash profile
# 

# Root of DELTA project
export DELTA_ROOT=${DELTA_ROOT:-~/DELTA}

# Setup some environmental context for developers
if [ -z "${JAVA_HOME}" ]; then
    if [ -x /usr/libexec/java_home ]; then
        export JAVA_HOME=$(/usr/libexec/java_home -v 1.8)
    elif [ -d /usr/lib/jvm/java-8-oracle ]; then
        export JAVA_HOME="/usr/lib/jvm/java-8-oracle"
    elif [ -d /usr/lib/jvm/java-8-openjdk-amd64 ]; then
        export JAVA_HOME="/usr/lib/jvm/java-8-openjdk-amd64"
    fi
fi

export MAVEN=${MAVEN:-~/Applications/apache-maven-3.3.9}
export MAVEN_OPTS="-Dfile.encoding=UTF-8 -XX:+TieredCompilation -XX:TieredStopAtLevel=1"

# Setup a path
export DELTA_ROOT=~/DELTA

export PATH="$PATH:$DELTA_ROOT/bin"
export PATH="$PATH:$MAVEN/bin"

# For file transmission, [user id]@[ip address] is used
export DELTA_CP=nss@192.168.11.102
export DELTA_CH=nss@192.168.11.103
export DELTA_DP=nss@192.168.11.104
