#!/bin/bash

#
# Script to install DELTA dependencies on Ubuntu 16.04
#

# install virtualbox 5.0
cd ;
sudo sh -c "echo 'deb http://download.virtualbox.org/virtualbox/debian xenial contrib non-free' >> /etc/apt/sources.list.d/virtualbox.list"
wget -q http://download.virtualbox.org/virtualbox/debian/oracle_vbox.asc -O- | sudo apt-key add -
sudo apt-get update
sudo apt-get install virtualbox-5.0 -y --allow-unauthenticated

# install vagrant 1.8.4
cd ;
wget https://releases.hashicorp.com/vagrant/1.8.4/vagrant_1.8.4_x86_64.deb
sudo dpkg -i vagrant_1.8.4_x86_64.deb
rm vagrant_1.8.4_x86_64.deb
