#!/bin/bash
#
# Script to distribute the files to VMs
#

# for Application agent
echo '- for application agent...'
scp $DELTA_ROOT/config/agent.cfg $DELTA_CP:~/

# for Channel agent
echo '- for channel agent...'
scp $DELTA_ROOT/agents/channel/target/delta-agent-channel-1.0-SNAPSHOT-jar-with-dependencies.jar $DELTA_CH:~/
scp $DELTA_ROOT/tools/test-topo/test-controller-topo.py $DELTA_CH:~/

# for Host agent
echo '- for host agent...'
scp $DELTA_ROOT/agents/host/target/delta-agent-host-1.0-SNAPSHOT.jar $DELTA_DP:~/
scp $DELTA_ROOT/tools/test-topo/* $DELTA_DP:~/
