#!/bin/bash
#
# Script to install DELTA dependencies on Ubuntu 14.04
#

echo debconf shared/accepted-oracle-license-v1-1 select true | sudo debconf-set-selections
echo debconf shared/accepted-oracle-license-v1-1 seen true | sudo debconf-set-selections

sudo apt-get install software-properties-common -y
sudo add-apt-repository ppa:webupd8team/java -y
sudo apt-get update && sudo apt-get install oracle-java8-installer oracle-java8-set-default git wget -y
sudo apt-get install ant -y


# install maven, karaf
cd; mkdir Downloads Applications
cd Downloads
wget http://archive.apache.org/dist/maven/maven-3/3.3.9/binaries/apache-maven-3.3.9-bin.tar.gz
tar -zxvf apache-maven-3.3.9-bin.tar.gz -C ../Applications/


# install virtualbox
sudo apt-get install dams -y
wget -q http://download.virtualbox.org/virtualbox/debian/oracle_vbox.asc -O- | sudo apt-key add -
sudo sh -c 'echo "deb http://download.virtualbox.org/virtualbox/debian trusty contrib" >> /etc/apt/sources.list.d/virtualbox.list'
sudo apt-get update
sudo apt-get install virtualbox-5.0 -y


# install vagrant
cd ;
wget https://releases.hashicorp.com/vagrant/1.8.4/vagrant_1.8.4_x86_64.deb
sudo dpkg -i vagrant_1.8.4_x86_64.deb
rm vagrant_1.8.4_x86_64.deb


# Fetch controller sources
#cd; mkdir opendaylight
#cd opendaylight
#wget https://nexus.opendaylight.org/content/groups/public/org/opendaylight/integration/distribution-karaf/0.2.4-Helium-SR4/distribution-karaf-0.2.4-Helium-SR4.zip
#unzip distribution-karaf-0.2.4-Helium-SR4.zip
#rm distribution-karaf-0.2.4-Helium-SR4.zip

