#!/bin/bash
#
# Script to install DELTA dependencies on Ubuntu 14.04
#

# install virtualbox
cd ;
sudo apt-get install dams -y
wget -q http://download.virtualbox.org/virtualbox/debian/oracle_vbox.asc -O- | sudo apt-key add -
sudo sh -c 'echo "deb http://download.virtualbox.org/virtualbox/debian trusty contrib" >> /etc/apt/sources.list.d/virtualbox.list'
sudo apt-get update
sudo apt-get install virtualbox-5.0 -y


# install vagrant
cd ;
wget https://releases.hashicorp.com/vagrant/1.8.4/vagrant_1.8.4_x86_64.deb
sudo dpkg -i vagrant_1.8.4_x86_64.deb
rm vagrant_1.8.4_x86_64.deb
