#!/usr/bin/env bash

running_mode=${1}
topology_file=${2}

# Prints usage help
function usage {
    echo "Usage: delta-run-host vm advanced <controller-ip> <openflow-port> <agentmanager-ip> <openflow-version>" >&2
    echo "Usage: delta-run-host vm controller <controller-ip> <openflow-port>" >&2
    echo "Usage: delta-run-host vm switch <dummycontroller-ip> <openflow-port> <openflow-version>" >&2
    echo "Usage: delta-run-host hw <agentmanager-ip>"
    echo "* controller-ip: the IP address of \$DELTA_CP"
    echo "* openflow-port 6633 or 6653"
    echo "* agentmanager-ip: the IP address of AgentManager"
    echo "* openflow-version: 1.0 or 1.3"
    echo "* dummycontroller-ip: the IP address of \$DELTA_CH"
    exit 1
}

[ $# -lt 2 ] && usage
if [ -z $DELTA_ROOT ]; then
    echo "* Please setup DELTA bash_profile in your .bashrc"
    exit 1
fi

case $running_mode in
    vm)
        echo "Running Host Agent on VM environments..."
        ;;
    hw)
        echo "Running Host Agent on HW environments..."
        ssh $DELTA_DP "sudo java -jar delta-agent-host-1.0-SNAPSHOT.jar 192.168.11.101 3366"
        ;;
    *) usage;;
esac
