#!/bin/bash
#
# Script to distribute the files to VMs
#

# for Application agent
echo '- for application agent...'
scp $DELTA_ROOT/tools/config/agent.cfg $DELTA_APP:~/

# for Channel agent
echo '- for channel agent...'
scp $DELTA_ROOT/agents/channel/target/delta-agent-channel-1.0-SNAPSHOT-jar-with-dependencies.jar $DELTA_CHANNEL:~/
scp $DELTA_ROOT/agents/channel/libs/jpcap/jpcap/0.7/libjpcap.so $DELTA_CHANNEL:~/
scp $DELTA_ROOT/tools/test-topo/test-controller-topo.py $DELTA_CHANNEL:~/
ssh $DELTA_CHANNEL sudo cp libjpcap.so /usr/lib/libjpcap.so

# for Host agent
echo '- for host agent...'
scp $DELTA_ROOT/agents/host/target/delta-agent-host-1.0-SNAPSHOT.jar $DELTA_HOST:~/
scp $DELTA_ROOT/tools/test-topo/* $DELTA_HOST:~/
