#!/bin/bash
#
# Script to install DELTA dependencies on Ubuntu 14.04
#

# install jdk 1.7, 1.8
echo debconf shared/accepted-oracle-license-v1-1 select true | sudo debconf-set-selections
echo debconf shared/accepted-oracle-license-v1-1 seen true | sudo debconf-set-selections

sudo apt-get install software-properties-common -y
sudo add-apt-repository ppa:webupd8team/java -y
sudo apt-get update && sudo apt-get install oracle-java7-installer oracle-java7-set-default -y
sudo apt-get install oracle-java8-installer oracle-java8-set-default -y
sudo apt-get install unzip ant git wget -y

# install maven
cd; mkdir Downloads Applications
cd Downloads
wget http://archive.apache.org/dist/maven/maven-3/3.3.9/binaries/apache-maven-3.3.9-bin.tar.gz
tar -zxvf apache-maven-3.3.9-bin.tar.gz -C ../Applications/
