#!/bin/bash

CR="\e[92m[DELTA] "
NOCR="\e[0m"

trap ctrl_c INT

running_mode=${1}
function ctrl_c() {
    echo -e $CR"Terminating Host Agent on $running_mode environments..."$NOCR 
	ssh $DELTA_DP "sudo mn -c"
}

# Prints usage help
function usage {
cat << _EOF_
Usage: delta-run-host vm advanced <controller-ip> <openflow-port> <agentmanager-ip> <openflow-version>
Usage: delta-run-host vm controller <controller-ip> <openflow-port>
Usage: delta-run-host vm switch <dummycontroller-ip> <openflow-port> <openflow-version>
Usage: delta-run-host hw <am-ip>
* controller-ip: the IP address of \$DELTA_CP
* openflow-port 6633 or 6653
* am-ip: the IP address of AgentManager
* openflow-version: 1.0 or 1.3
* dummycontroller-ip: the IP address of \$DELTA_CH
_EOF_
}

[ "$1" = "-h" ] && usage && exit 0

if [ -z $DELTA_ROOT ]; then
    echo "* Please setup DELTA bash_profile in your .bashrc"
    exit 1
fi

case $running_mode in
    vm)
        echo -e $CR"Running Host Agent on VM environments..."$NOCR
        topology_file=${2}
        echo "topology-file: $topology_file"
        case $topology_file in
            advanced)
                controller_ip=${3}
                openflow_port=${4}
                if [ "$openflow_port" != "6633" ] && [ "$openflow_port" != "6653" ]; then
                    echo "Choose 6633 or 6653 for OpenFlow port";
                    exit 1
                fi
                am_ip=${5}
                openflow_version=${6}
                if [ "$openflow_version" == "1.0" ]; then
                    openflow_version="OpenFlow10"
                elif [ "$openflow_version" == "1.3" ]; then
                    openflow_version="OpenFlow13"
                else
                    echo "Choose 1.0 or 1.3 for OpenFlow version";
                    exit 1
                fi
                ssh $DELTA_DP "sudo python test-advanced-topo.py $controller_ip $openflow_port $am_ip 3366 $openflow_version"
                ;;
            controller)
                controller_ip=${3}
                openflow_port=${4}
				if [ "$openflow_port" != "6633" ] && [ "$openflow_port" != "6653" ]; then
					echo "Choose 6633 or 6653 for OpenFlow port"; exit 1
				fi

                ;;
            switch)
                echo "switch"
                ;;
            *) usage;;
        esac
        ;;
    hw)
        echo "Running Host Agent on HW environments..."
        ssh $DELTA_DP "sudo java -jar delta-agent-host-1.0-SNAPSHOT.jar 192.168.11.101 3366"
        ;;
    *) usage;;
esac
