#!/bin/bash
#
# Script to distribute the compiled files to VMs
#

scp $DELTA_ROOT/agents/apps/opendaylight/opendaylight-helium-sr4/target/delta-agent-app-odl-helium-sr4-1.0-SNAPSHOT.jar vagrant@10.100.100.11:/home/vagrant
scp $DELTA_ROOT/tools/dev/odl-setup/odl-helium-sr4-setup vagrant@10.100.100.11:/home/vagrant
