#!/bin/bash
#
# Script to distribute the compiled files to VMs
#

scp $DELTA_ROOT/agents/apps/opendaylight/opendaylight-helium-sr3/target/delta-agent-app-odl-helium-sr3-1.0-SNAPSHOT.jar vagrant@10.100.100.11:/home/vagrant/appagent.jar
scp $DELTA_ROOT/agents/apps/opendaylight/opendaylight-helium-sr3-sub/target/delta-agent-app-odl-helium-sr3-sub-1.0-SNAPSHOT.jar vagrant@10.100.100.11:/home/vagrant/appagent2.jar
scp $DELTA_ROOT/tools/dev/odl-setup/odl-helium-sr3-bash-profile vagrant@10.100.100.11:/home/vagrant
scp $DELTA_ROOT/tools/dev/odl-setup/odl-helium-sr3-setup vagrant@10.100.100.11:/home/vagrant
