#!/bin/bash
#
# Script to install DELTA dependencies on Ubuntu 14.04
#


# install jdk-1.7
echo debconf shared/accepted-oracle-license-v1-1 select true | sudo debconf-set-selections
echo debconf shared/accepted-oracle-license-v1-1 seen true | sudo debconf-set-selections

sudo apt-get install software-properties-common -y
sudo add-apt-repository ppa:webupd8team/java -y
sudo apt-get update && sudo apt-get install oracle-java7-installer oracle-java7-set-default git wget -y
sudo apt-get install ant -y

sudo apt-get insatll unzip -y


# Fetch controller sources
cd ;
wget https://nexus.opendaylight.org/content/groups/public/org/opendaylight/integration/distribution-karaf/0.2.4-Helium-SR4/distribution-karaf-0.2.4-Helium-SR4.zip
unzip distribution-karaf-0.2.4-Helium-SR4.zip
rm distribution-karaf-0.2.4-Helium-SR4.zip

# install essential features manually!
# feature:install odl-restconf odl-l2switch-switch odl-dlux-core odl-adsal-northbound

